AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketStack:
    Type: String
    Default: cross-stack-bucket
Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0182f373e66f89c85"
      InstanceType: t2.micro
      Tags:
        - Key: AssociatedBucket
          Value: 
            Fn::ImportValue:
              !Sub "BucketName-${BucketStack}"