#!/usr/bin/env bash
set -e

# we need the absolute path because relative path was giving us trouble
root_path=$(realpath .)
template_path="${root_path}/template.yaml"
#config_path="$(realpath ..)/python.toml"

#if [ ! -f "$config_path" ]; then
#  echo "$config_path does not exist."
#  exit 1
#fi

# sam deploy
# ===================
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html
# -------------------
echo "== SAM deploy..."
#echo "loading configuration: $config_path"

sam deploy \
  --template-file $template_path \
  --stack-name "db-table-sam" \
  --capabilities "CAPABILITY_IAM"
  #--config-file "$config_path" \s