AWSTemplateFormatVersion: "2010-09-09"
Description: fifo standard test
Resources: 
  MyQueue: 
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
    Type: AWS::SQS::Queue
    Properties: 
      FifoQueue: true
      QueueName: "FifoStandardTest.fifo"