#!/usr/bin/env bash

STACK_NAME="root-stack"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy/index.html
aws cloudformation deploy \
--template-file root-template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region us-east-1 \
--stack-name $STACK_NAME