AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Type: String
    Default: andresmup-s3-bycket-from-nested-stack
Resources:
  S3Bucket:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName