---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create in the order of 2, 3 and then 1
Parameters:
  Subnets: 
    Description: Subnet IDs
    Type: "List<AWS::EC2::Subnet::Id>"
    Default: "subnet-02207f9fc63571a2a,subnet-01668d4e4573f5b0d"
Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0182f373e66f89c85"
      InstanceType: t3.micro
Outputs:
  InstanceId:
    Description: InstanceId
    Value: 
      !Ref MyEC2Instance
      # Fn::Ref MyEC2Instance
    Export:
      Name: InstanceId
  VpcId:
    Description: VpcId
    Value: 
      !GetAtt MyEC2Instance.VpcId
      # Fn::GetAtt MyEC2Instance
  VPCArn:
    Description: VpcId
    Value: 
      !Sub 
        - 'arn:aws:ec2:${REGION}:${ACCOUNT_ID}:vpc/${VPC_ID}'
        - ACCOUNT_ID: !Ref AWS::AccountId
          REGION: !Ref AWS::Region
          VPC_ID: !GetAtt MyEC2Instance.VpcId
  JoinsSubnets:
    Description: JoinsSubnets
    Value: 
      !Join
        - ','
        - !Ref Subnets
  #Splits:
  #  Description: Splits
  #  Value: 
  #    !Split [ "," , "a,b,c" ]
  #  Export:
  #    Name: Splits